CREATE DATABASE board11;
USE board11;
CREATE TABLE t_board(
	i_board INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(200) NOT NULL,
	ctnt VARCHAR(3000) NOT NULL,
	created_at DATETIME DEFAULT NOW(),
	mod_at DATETIME DEFAULT NOW()
);
